import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import FnFHeader from "../../../components/FnFHeader";
import { http } from "../../../core/helpers/http";
import Layout from "../../../layout/Layout";

const following = () => {
  const [profile, setProfile] = useState<any>();
  const router = useRouter();
  const { id } = router.query;
  useEffect(() => {
    http
      .get("users/" + id)
      .then((res) => {
        setProfile(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, [id]);
  return (
    <>
      <Head>
        <title>{profile && profile.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FnFHeader query={id} name={profile && profile.name} />
      </Layout>
    </>
  );
};

export default following;
