import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import FnFHeader from "../../../components/FnFHeader";
import FnfProfile from "../../../components/FnfProfile";
import { getOneUser } from "../../../core/services/user.service";
import { ISuggestionsProfile } from "../../../interfaces/ISuggestionProfile";
import Layout from "../../../layout/Layout";

const follower = () => {
  const [profile, setProfile] = useState<any>();
  const followers: ISuggestionsProfile[] = profile && profile.followers;
  const router = useRouter();
  const { id } = router.query;
  useEffect(() => {
    getOneUser(id)
      .then((res) => {
        setProfile(res.data);
      })
      .catch((err) => console.log(err));
  }, [id]);
  return (
    <>
      <Head>
        <title>{profile && profile.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FnFHeader type="followers" query={id} name={profile && profile.name} />
        <div className="followers-wrapper">
          {followers &&
            followers.map((follower, _) => (
              <FnfProfile key={_} profile={follower} />
            ))}
        </div>
      </Layout>
    </>
  );
};

export default follower;
