import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className=" text-red-600">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod
          distinctio illo consequatur? Placeat harum architecto maxime
          asperiores nesciunt, nam reiciendis. Saepe officiis quibusdam incidunt
          molestiae ad sapiente est, reprehenderit ut!
        </p>
      </main>
    </div>
  );
};

export default Home;
