import type { NextPage } from "next";
import Head from "next/head";
import Post from "../components/Post";
import Layout from "../layout/Layout";
// import { Scrollbars } from "react-custom-scrollbars";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PqSocial | Feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="rounded-xl p-3 mt-5 bg-white">
          <div className="w-full flex gap-2 items-center">
            <div className="w-10 rounded-full cursor-pointer overflow-hidden h-10">
              <img
                className="w-full h-full object-center object-cover"
                src="https://images.unsplash.com/photo-1519058082700-08a0b56da9b4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fG1lbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60"
                alt=""
              />
            </div>
            <input
              type="text"
              placeholder="Express your thoughts...."
              className="w-11/12 outline-none text-[13px] rounded-xl placeholder:text-xs placeholder:text-secondary p-[10px] bg-primary"
            />
          </div>
          <div className="flex items-center gap-5 mt-4">
            <div className="flex p-1 px-2 transition-all hover:bg-gray-100/70 rounded-md cursor-pointer items-center gap-2">
              <img className="w-7 h-7" src="/photos.png" alt="" />
              <h2 className="text-sm font-medium text-secondary">
                Share a Photo
              </h2>
            </div>
            <div className="flex p-1 px-2 transition-all hover:bg-gray-100/70 rounded-md cursor-pointer items-center gap-2">
              <img className="w-7 h-7" src="/article.png" alt="" />
              <h2 className="text-sm font-medium text-secondary">
                Write a Article
              </h2>
            </div>
            <div className="flex p-1 px-2 transition-all hover:bg-gray-100/70 rounded-md cursor-pointer items-center gap-2">
              <img className="w-7 h-7" src="/video.png" alt="" />
              <h2 className="text-sm font-medium text-secondary">
                Share a Video
              </h2>
            </div>
          </div>
        </div>
        <div className="posts-wrapper flex items-center flex-col gap-5 my-7">
          <Post />
          <Post />
          <Post />
        </div>
      </Layout>
    </div>
  );
};

export default Home;
