import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../layout/Layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatum
        voluptatem est, sit velit delectus dolorem sunt reprehenderit. Quia
        voluptatem nostrum voluptatibus! Beatae distinctio voluptatem id
        perspiciatis. Totam vitae neque a?
      </Layout>
    </div>
  );
};

export default Home;
