import { Button, Form, Input } from "antd";
import axios from "axios";
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { API_URL } from "../core/config/environment";
import AuthLayout from "../layout/AuthLayout";

const SignUp: NextPage = () => {
  const router = useRouter();
  const [form] = Form.useForm();
  const handleSubmit = (values: any): void => {
    axios
      .post(API_URL + "users/signup", {
        ...values,
      })
      .then((res) => {
        console.log(res);
      })
      .catch((err) => console.log(err));
  };
  return (
    <>
      <Head>
        <title>Create an Account | Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout>
        <img className="mb-4" src="/twitter.png" alt="" />
        <h1 className="text-5xl font-bold">Explore whats happening</h1>
        <div className="form-wrapper w-7/12 pt-14">
          <Form onFinish={handleSubmit} form={form} layout="vertical">
            <Form.Item
              rules={[{ required: true, message: "Please input your email!" }]}
              name={"email"}
              label="Email Address"
            >
              <Input placeholder="Enter your email address" />
            </Form.Item>
            <Form.Item
              rules={[
                { required: true, message: "Please input your username!" },
              ]}
              name={"username"}
              label="Username"
            >
              <Input placeholder="Enter your username" />
            </Form.Item>
            <Form.Item
              rules={[{ required: true, message: "Please input your name!" }]}
              name={"name"}
              label="Name"
            >
              <Input placeholder="Enter your name" />
            </Form.Item>
            <Form.Item
              name={"password"}
              rules={[
                { required: true, message: "Please input your password!" },
              ]}
              label="Password"
            >
              <Input.Password placeholder="Password" />
            </Form.Item>
            <Form.Item>
              <div className="flex items-center gap-3">
                <Button className="primary-btn" htmlType="submit">
                  Submit
                </Button>
                <span
                  onClick={() => {
                    router.push("/login");
                  }}
                  className="text-blue-400 text-xs cursor-pointer"
                >
                  Already have an account?
                </span>
              </div>
            </Form.Item>
          </Form>
        </div>
      </AuthLayout>
      ;
    </>
  );
};

export default SignUp;
